---
abstract: "Dancer2's plugin for WWW::Sixpack"
author:
  - 'Menno Blom <blom@cpan.org>'
build_requires:
  Dancer2::Test: 0
  Test::LWP::UserAgent: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Sixpack
no_index:
  directory:
    - t
    - inc
requires:
  Dancer2: 0
  WWW::Sixpack: 0.02
  perl: 5.006
resources:
  repository: https://github.com/b10m/p5-Dancer2-Plugin-Sixpack
version: 0.02
